apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-kibana-config
  namespace: saif
  labels:
    app: kibana
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["http://elasticsearch.saif.svc.cluster.local:9200"]
    elasticsearch.username: "kibana_user"
    elasticsearch.password: "password"
