apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: saif
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  clusterIP: None
  ports:
  - port: 9200
    name: rest
  - port: 9300
    name: inter-node
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch-ingress
  namespace: saif
spec:
  tls:
  - hosts:
    - elasticsearch.test.com
  ingressClassName: contour
  rules:
  - host: elasticsearch.test.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elasticsearch
            port:
              number: 9200
