apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: saif
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Parsers_File  /fluent-bit/etc/parsers.conf

    [INPUT]
        Name          tail
        Path          /var/log/containers/nginx*.log
        Tag           kubernetes.nginx
        DB            /var/log/fluent-bit-nginx.db
        Parser        nginx_parser

    [FILTER]
        Name          kubernetes
        Match         kubernetes.*
        Merge_Log     On

    [OUTPUT]
        Name          es
        Match         kubernetes.nginx
        Host          elasticsearch.saif.svc.cluster.local
        Port          ${FLUENT_ELASTICSEARCH_PORT}
        HTTP_User     ${FLUENT_ELASTICSEARCH_USER}
        HTTP_Passwd   password
        Index         fluent-bit
        Type          _doc
        tls           off

  parsers.conf: |
    [PARSER]
        Name          nginx_parser
        Format        regex
        Regex         ^(?<remote_ip>[^ ]*) - - \[(?<timestamp>\d{2}\/[A-Za-z]{3}\/\d{4}:\d{2}:\d{2}:\d{2} [+\-]\d{4})\] "(?<request_method>[A-Z]+) (?<path>[^ ]*) HTTP\/1\.[01]" (?<status>\d{3}) (?<size>\d+) "(?<referrer>[^"]*)" "(?<user_agent>[^"]*)"
        Time_Key      timestamp
        Time_Format   %d/%b/%Y:%H:%M:%S %z
